---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-svc
  labels:
    app: verification-svc
    kots.io/placeholder: "true"
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harness-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-engine
  labels:
    app: learning-engine
    kots.io/placeholder: "true"
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harness-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-ui
  labels:
    kots.io/placeholder: "true"
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harness-registry
