apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
commonAnnotations:
  kots.io/app-slug: harness-ng
images:
- name: docker.io/harness/cdcdata-signed
  newName: proxy.replicated.com/proxy/harness-ng/harness/cdcdata-signed
- name: harness/cdcdata-signed
  newName: proxy.replicated.com/proxy/harness-ng/harness/cdcdata-signed
- name: docker.io/harness/ci-manager-signed
  newName: proxy.replicated.com/proxy/harness-ng/harness/ci-manager-signed
- name: harness/ci-manager-signed
  newName: proxy.replicated.com/proxy/harness-ng/harness/ci-manager-signed
- name: docker.io/harness/cv-nextgen
  newName: proxy.replicated.com/proxy/harness-ng/harness/cv-nextgen
- name: harness/cv-nextgen
  newName: proxy.replicated.com/proxy/harness-ng/harness/cv-nextgen
- name: docker.io/harness/le-nextgen-signed
  newName: proxy.replicated.com/proxy/harness-ng/harness/le-nextgen-signed
- name: harness/le-nextgen-signed
  newName: proxy.replicated.com/proxy/harness-ng/harness/le-nextgen-signed
- name: docker.io/harness/template-service-signed
  newName: proxy.replicated.com/proxy/harness-ng/harness/template-service-signed
- name: harness/template-service-signed
  newName: proxy.replicated.com/proxy/harness-ng/harness/template-service-signed
- name: docker.io/harness/ti-service-signed
  newName: proxy.replicated.com/proxy/harness-ng/harness/ti-service-signed
- name: harness/ti-service-signed
  newName: proxy.replicated.com/proxy/harness-ng/harness/ti-service-signed
kind: Kustomization
patchesStrategicMerge:
- pullsecrets.yaml
resources:
- secret.yaml
transformers:
- backup-label-transformer.yaml
