---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: change-data-capture
  labels:
    app: change-data-capture
    kots.io/placeholder: "true"
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harness-ng-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-manager
  labels:
    app: ci-manager
    kots.io/placeholder: "true"
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harness-ng-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-nextgen
  labels:
    app: cv-nextgen
    kots.io/placeholder: "true"
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harness-ng-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: le-nextgen
  labels:
    app: le-nextgen
    kots.io/placeholder: "true"
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harness-ng-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-service
  labels:
    app: template-service
    kots.io/placeholder: "true"
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harness-ng-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ti-service
  labels:
    app: ti-service
    kots.io/placeholder: "true"
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harness-ng-registry
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ti-migration-release-46
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harness-ng-registry
