apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: access-control
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: 'harness'
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    kots.io/placeholder: 'true'
      
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: access-control
              servicePort: 9006
            path: /authz(/|$)(.*)  
#          