apiVersion: v1
kind: ConfigMap
metadata:
  name: access-control
data:
  DEPLOY_MODE: KUBERNETES_ONPREM
  LOGGING_LEVEL: 'INFO' 
  EVENTS_CONFIG_USE_SENTINEL: 'true'
  EVENTS_CONFIG_SENTINEL_MASTER_NAME: 'harness-redis'
  EVENTS_CONFIG_REDIS_SENTINELS: 'redis://redis-sentinel-harness-announce-0.harness:26379,redis://redis-sentinel-harness-announce-1.harness:26379,redis://redis-sentinel-harness-announce-2.harness:26379'

  # lockRedisConfig
  LOCK_CONFIG_USE_SENTINEL: 'true'
  LOCK_CONFIG_SENTINEL_MASTER_NAME: 'harness-redis'
  LOCK_CONFIG_REDIS_SENTINELS: 'redis://redis-sentinel-harness-announce-0.harness:26379,redis://redis-sentinel-harness-announce-1.harness:26379,redis://redis-sentinel-harness-announce-2.harness:26379'

  # iteratorsConfig
  RESOURCE_GROUP_ITERATOR_ENABLED: 'true'
  RESOURCE_GROUP_ITERATOR_INTERVAL: '3600'
  USER_GROUP_ITERATOR_ENABLED: 'true'
  USER_GROUP_ITERATOR_INTERVAL: '3600'
  USER_ITERATOR_ENABLED: 'true'
  USER_ITERATOR_INTERVAL: '3600'
  SERVICEACCOUNT_ITERATOR_ENABLED: 'true'
  SERVICEACCOUNT_ITERATOR_INTERVAL: '3600'
  SUPPORTPREFERENCE_ITERATOR_ENABLED: 'true'
  SUPPORTPREFERENCE_ITERATOR_INTERVAL: '600'
  SCOPE_ITERATOR_ENABLED: 'true'
  SCOPE_ITERATOR_INTERVAL: '3600'

  # resourceGroupClient:
  RESOURCE_GROUP_CLIENT_BASE_URL: '35.202.24.14/resourcegroup/api/'

  # userClient:
  USER_CLIENT_BASE_URL: '35.202.24.14/ng/api/'

  # userGroupClient
  USER_GROUP_CLIENT_BASE_URL: '35.202.24.14/ng/api/'

  # serviceAccountClient
  SERVICEACCOUNT_CLIENT_BASE_URL : '35.202.24.14/ng/api/'

  #accountClient
  ACCOUNT_CLIENT_BASE_URL: '35.202.24.14/api/'
  FEATURE_FLAG_CLIENT_BASE_URL: '35.202.24.14/api/'

  #projectClient
  PROJECT_CLIENT_BASE_URL: '35.202.24.14/ng/api/'

  #organizationClient
  ORGANIZATION_CLIENT_BASE_URL: '35.202.24.14/ng/api/'

  # aggreatorModuleConfig
  OFFSET_FLUSH_INTERVAL_MS: '10000'
  MONGODB_HOSTS: 'mongodb-replicaset-chart-0.mongodb-replicaset-chart.harness.svc:27017'
  MONGODB_USER: admin
  MONGODB_SSL_ENABLED: 'false'
  AGGREGATOR_ENABLED: 'true'

  # auth
  ENABLE_AUTH: 'true'

  # preference
  ACCESS_CONTROL_PREFERENCE_ENABLED: 'true'

  #for notification
  NOTIFICATION_SLACK_WEBHOOK_URL: ''
  NOTIFICATION_ENVIRONMENT: ONPREM


  # for client
  ENABLE_ACCESS_CONTROL: 'false'
  ACCESS_CONTROL_SERVICE_BASE_URL: '35.202.24.14/authz/api/'

  ENABLE_AUDIT: 'true'
  AUDIT_CLIENT_BASE_URL: '35.202.24.14/audit/api/'

  DISTRIBUTED_LOCK_IMPLEMENTATION: redis

  GOOGLE_APPLICATION_CREDENTIALS: /opt/harness/monitoring/stackdriver.json