apiVersion: apps/v1
kind: Deployment
metadata:
  name: change-data-capture
  labels:
    app: change-data-capture
    kots.io/placeholder: 'true'
    
  annotations:  
    kots.io/placeholder: 'true'
        
spec:
  replicas: 1
  selector:
    matchLabels:
      app: change-data-capture
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: change-data-capture
        kots.io/placeholder: 'true'
        
      annotations:
        kots.io/placeholder: 'true'
                
    spec:
# 
      serviceAccountName: harness-default      
      terminationGracePeriodSeconds: 30
      containers:
      - name: change-data-capture
        image: harness/cdcdata-signed:74410
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 65534
          runAsNonRoot: true        
        envFrom:
        - configMapRef:
            name: change-data-capture
        - secretRef:
            name: change-data-capture
        resources:
          limits:
            memory: '2880Mi'
            cpu: '0.5'
          requests:
            memory: '2880Mi'
            cpu: '0.5'
        readinessProbe:
          httpGet:
            path: /health
            port: 8190
          initialDelaySeconds: 300
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /health
            port: 8190
          initialDelaySeconds: 400
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 10

