
apiVersion: v1
kind: Service
metadata:
  name: ci-manager
  labels:
    kots.io/placeholder: 'true'
     
spec:
  type: ClusterIP
  ports:
  - name: ci-manager
    port: 7090
    protocol: TCP
    targetPort: 7090
  - name: ci-manager-grpc
    port: 9979
    protocol: TCP
    targetPort: 9979     
  selector:
    app: ci-manager
