apiVersion: v1
kind: Service
metadata:
  name: cv-nextgen
spec:
  ports:
    - name: cv
      port: 6060
      protocol: TCP
      targetPort: cv
    - name: cv-nextgen-grpc
      port: 9979
      protocol: TCP
      targetPort: 9979
  selector:
    app: cv-nextgen
  type: ClusterIP