
apiVersion: v1
kind: Service
metadata:
  name: log-service
  labels:
    kots.io/placeholder: 'true'
    
spec:
  type: ClusterIP
  ports:
  - name: log-service
    port: 8079
    protocol: TCP
    targetPort: 8079
  selector:
    app: log-service