
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: log-service
stringData:
  LOG_SERVICE_S3_ACCESS_KEY_ID: 'minio'
  LOG_SERVICE_S3_SECRET_ACCESS_KEY: 'minio123'
  LOG_SERVICE_GLOBAL_TOKEN: c76e567a-b341-404d-a8dd-d9738714eb82
  LOG_SERVICE_SECRET: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM