
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
  labels:
    app: log-service
    kots.io/placeholder: 'true'
    
  annotations:  
    kots.io/placeholder: 'true'
        
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  selector:
    matchLabels:
      app: log-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate          
  template:
    metadata:
      labels:
        app: log-service
        kots.io/placeholder: 'true'
        
      annotations:
        kots.io/placeholder: 'true'
                
    spec:
      terminationGracePeriodSeconds: 30
#                 
      serviceAccountName: harness-default      
      containers:
      - envFrom:
        - configMapRef:
            name: log-service
        - secretRef:
            name: log-service
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-log-svc
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: http-log-svc
          initialDelaySeconds: 10
          periodSeconds: 10
        name: log-service
        image: harness/log-service-signed:release-18
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 65534
          runAsNonRoot: true
        ports:
        - name: http-log-svc
          containerPort: 8079
          protocol: "TCP"    
        resources:
          limits:
            memory: '1400Mi'
            cpu: '0.5'
          requests:
            memory: '1400Mi'
            cpu: '0.5'