
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    kots.io/placeholder: 'true'
    
  labels:
    app: log-service-minio
    kots.io/placeholder: 'true'
    
  name: log-service-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-service-minio
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: log-service-minio
        kots.io/placeholder: 'true'
        
      annotations:
        kots.io/placeholder: 'true'
                
      name: log-service-minio
    spec:
      containers:
      - command:
        - /bin/sh
        - -ce
        - /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server /data
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: log-service-minio
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: log-service-minio
        image: minio/minio:RELEASE.2022-01-08T03-11-54Z
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /minio/health/live
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: log-service-minio
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /minio/health/ready
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: "1"
            memory: 4Gi
        volumeMounts:
        - mountPath: /data
          name: data
      serviceAccountName: harness-default
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - name: minio-user
        secret:
          defaultMode: 420
          secretName: log-service-minio
      - name : data 
        persistentVolumeClaim:
          claimName: log-service-minio
