
apiVersion: v1
kind: Service
metadata:
  labels:
    app: log-service-minio
    kots.io/placeholder: 'true'
    
  name: log-service-minio
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: log-service-minio
  sessionAffinity: None
  type: ClusterIP