
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-service-minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '10Gi'
  storageClassName: 'standard'