

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: next-gen-ui
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: 'harness'
    kots.io/placeholder: 'true'
    
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: next-gen-ui
              servicePort: 80
            path: /ng(/|$)(.*)
#                  