
apiVersion: v1
kind: Service
metadata:
  name: next-gen-ui
  labels:
    kots.io/placeholder: 'true'
    
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: next-gen-ui
  sessionAffinity: None  