
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ng-manager
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: 'harness'
    kots.io/placeholder: 'true'
    
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: ng-manager
              servicePort: 7090
            path: /ng/api(/|$)(.*)
#            
          