apiVersion: v1
kind: Service
metadata:
  name: ng-manager
  labels:
    kots.io/placeholder: 'true'
    
spec:
  ports:
  - name: http-ng-manager
    port: 7090
    protocol: TCP
    targetPort: 7090
  - name: ng-manager-grpc
    port: 9979
    protocol: TCP
    targetPort: 9979
  - name: git-sync-grpc
    port: 13002
    protocol: TCP
    targetPort: 13002     
  selector:
    app: ng-manager
  sessionAffinity: None
  type: ClusterIP    