
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pipeline-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: 'harness'
    kots.io/placeholder: 'true'
    
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: pipeline-service
              servicePort: 12001
            path: /pipeline(/|$)(.*)
#            
          