apiVersion: v1
kind: Service
metadata:
  name: platform-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9005
    protocol: TCP
    targetPort: 9005
  selector:
    app: platform-service