apiVersion: v1
kind: Service
metadata:
  name: scm
  labels:
    kots.io/placeholder: 'true'
    
spec:
  ports:
  - name: scm
    port: 8091
    protocol: TCP
    targetPort: 8091
  selector:
    app: scm
  type: ClusterIP