
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scm
  labels:
    kots.io/placeholder: 'true'
    
  annotations:  
    kots.io/placeholder: 'true'
        
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scm
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: scm
        kots.io/placeholder: 'true'
        
      annotations:
        license-features-hash: 'abc43bfad2c3c7274b66e21b998f581bf20ac8979a3705db18b8afec24d5f109'
        kots.io/placeholder: 'true'
           
    spec:
#                 
      serviceAccountName: harness-default
      containers:
      - name: scm
        image: harness/ci-scm-signed:release-45
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 65534
          runAsNonRoot: true
        ports:
        - name: scm
          containerPort: 8091
          protocol: TCP
        resources:
          limits:
            memory: '512Mi'
            cpu: '0.1'
          requests:
            memory: '512Mi'
            cpu: '0.1'
        readinessProbe:
          exec:
            command: ["/grpc_health_probe", "-addr=:8091"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/grpc_health_probe", "-addr=:8091"]
          initialDelaySeconds: 10