
apiVersion: v1
kind: Service
metadata:
  name: template-service
  labels:
    kots.io/placeholder: 'true'
    
spec:
  type: ClusterIP
  ports:
    - name: template-grpc
      port: 15011
      protocol: TCP
      targetPort: 15011
    - name: template-http
      port: 15001
      protocol: TCP
      targetPort: 15001
    - name: gitsync-grpc
      port: 16002
      protocol: TCP
      targetPort: 16002
  selector:
    app: template-service