apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: template-service
stringData:
  MONGO_URI: 'mongodb://admin:CA8FMywpbM@mongodb-replicaset-chart-0.mongodb-replicaset-chart.harness.svc/template-harness?authSource=admin'