
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ti-service
  labels:
    app: ti-service
    kots.io/placeholder: 'true'
    
  annotations:  
    kots.io/placeholder: 'true'
        
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ti-service
  template:
    metadata:
      labels:
        app: ti-service
        kots.io/placeholder: 'true'
        
      annotations:
        kots.io/placeholder: 'true'
                
    spec:
#                 
      serviceAccountName: harness-default
      terminationGracePeriodSeconds: 30
      containers:
      - envFrom:
        - secretRef:
            name: ti-service
        - configMapRef:
            name: ti-service
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-ti-service
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: http-ti-service
          initialDelaySeconds: 10
          periodSeconds: 10
        name: ti-service
        image: harness/ti-service-signed:release-46
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 65534
          runAsNonRoot: true
        ports:
        - name: http-ti-service
          containerPort: 8078
          protocol: "TCP"    
        resources:
          limits:
            memory: '1400Mi'
            cpu: '0.5'
          requests:
            memory: '1400Mi'
            cpu: '0.5'