apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- harness/defaul-backend-2.yaml
- harness/defaul-backend.yaml
- harness/harness-gateway-2.yaml
- harness/harness-gateway-3.yaml
- harness/harness-gateway-4.yaml
- harness/harness-gateway-5.yaml
- harness/harness-gateway.yaml
- harness/harness-ingress-controller-2.yaml
- harness/harness-ingress-controller-3.yaml
- harness/harness-ingress-controller-4.yaml
- harness/harness-ingress-controller-5.yaml
- harness/harness-ingress-controller-6.yaml
- harness/harness-ingress-controller-7.yaml
- harness/harness-ingress-controller.yaml
- harness/harness-manager-2.yaml
- harness/harness-manager-3.yaml
- harness/harness-manager-4.yaml
- harness/harness-manager-5.yaml
- harness/harness-manager-6.yaml
- harness/harness-manager-7.yaml
- harness/harness-manager-8.yaml
- harness/harness-manager-9.yaml
- harness/harness-manager.yaml
- harness/harness-storage-proxy-2.yaml
- harness/harness-storage-proxy-3.yaml
- harness/harness-storage-proxy-4.yaml
- harness/harness-storage-proxy.yaml
- harness/harness-verification-svc-2.yaml
- harness/harness-verification-svc-3.yaml
- harness/harness-verification-svc-4.yaml
- harness/harness-verification-svc-5.yaml
- harness/harness-verification-svc.yaml
- harness/learning-engine-2.yaml
- harness/learning-engine-3.yaml
- harness/learning-engine.yaml
- harness/mongodb-2.yaml
- harness/mongodb-3.yaml
- harness/mongodb-4.yaml
- harness/mongodb-5.yaml
- harness/mongodb-7.yaml
- harness/mongodb-8.yaml
- harness/ng-auth-ui-2.yaml
- harness/ng-auth-ui-3.yaml
- harness/ng-auth-ui-4.yaml
- harness/ng-auth-ui.yaml
- harness/redis-2.yaml
- harness/redis-3.yaml
- harness/redis-4.yaml
- harness/redis-5.yaml
- harness/redis-6.yaml
- harness/redis.yaml
- harness/timescaledb-10.yaml
- harness/timescaledb-11.yaml
- harness/timescaledb-2.yaml
- harness/timescaledb-3.yaml
- harness/timescaledb-4.yaml
- harness/timescaledb-5.yaml
- harness/timescaledb-6.yaml
- harness/timescaledb-7.yaml
- harness/timescaledb-8.yaml
- harness/timescaledb-9.yaml
- harness/timescaledb.yaml
- harness/ui-2.yaml
- harness/ui-3.yaml
- harness/ui-4.yaml
- harness/ui.yaml
