kind: Deployment
apiVersion: apps/v1
metadata:
  name: default-backend
  annotations:
    "kots.io/exclude": 'false'
    kots.io/placeholder: 'true'
    
  labels:
    kots.io/placeholder: 'true'
      
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-backend
  template:
    metadata:
      labels:
        app: default-backend
        kots.io/placeholder: 'true'
        
      annotations:
        kots.io/placeholder: 'true'
           
    spec:
      serviceAccountName: harness-serviceaccount
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend
        image: k8s.gcr.io/defaultbackend-amd64:1.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        securityContext:
          runAsUser: 65534    
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP