
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: harness-role-hsa-binding
  annotations:
    "kots.io/exclude": 'false'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: harness-role
subjects:
  - kind: ServiceAccount
    name: harness-serviceaccount
    namespace: 'harness'