apiVersion: v1
kind: ConfigMap
metadata:
  name: harness-gateway
data:
  MANAGER_URL: 'http://35.202.24.14'
  MANAGER_PUBLIC_URL: 'http://35.202.24.14'
  MEMORY: '1024'
  DEPLOY_MODE: KUBERNETES_ONPREM
  API_VERSION: 'release-gateway:182'
  LOG_SVC_GLOBAL_TOKEN: c76e567a-b341-404d-a8dd-d9738714eb82
  TI_SVC_GLOBAL_TOKEN: 78d16b66-4b4c-11eb-8377-acde48001122
  CACHE_TYPE: REDIS
  TOKEN_CACHE_TTL: '300'
  USE_SENTINEL: 'true'
  SENTINEL_MASTER_NAME: 'harness-redis'
  REDIS_PORT: '26379'
  REDIS_SENTINELS: 'redis-sentinel-harness-announce-0.harness,redis-sentinel-harness-announce-1.harness,redis-sentinel-harness-announce-2.harness'