apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: verification-svc
stringData:
  VERIFICATION_SERVICE_SECRET: 59MR5RlVARcdH7zb7pNx6GzqiglBmXR8
  MONGO_URI: 'mongodb://admin:CA8FMywpbM@mongodb-replicaset-chart-0.mongodb-replicaset-chart.harness.svc.cluster.local/harness?authSource=admin'