

apiVersion: v1
kind: Service
metadata:
  name: verification-svc
  labels:
    kots.io/placeholder: 'true'
     
spec:
  ports:
    - name: verification
      port: 7070
      protocol: TCP
      targetPort: 7070
  selector:
    app: verification-svc
  sessionAffinity: None
  type: ClusterIP
