apiVersion: v1
kind: Secret
metadata:
  name: harness-gateway
stringData:
  MONGO_DB_URL: 'mongodb://admin:CA8FMywpbM@mongodb-replicaset-chart-0.mongodb-replicaset-chart.harness.svc/gateway?authSource=admin' 
type: Opaque