
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb-replicaset
    kots.io/placeholder: 'true'
    
  annotations:  
    kots.io/placeholder: 'true'
           
  name: mongodb-replicaset-chart
spec:
  selector:
    matchLabels:
      app: mongodb-replicaset
  serviceName: mongodb-replicaset-chart
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-replicaset
        kots.io/placeholder: 'true'
         
      annotations:
        kots.io/placeholder: 'true'
         
        checksum/config: fca3516170d327de50810cf50494e20bed3e41732799a291de1d1563b1a247cf
        backup.velero.io/backup-volumes: datadir       
    spec:
#                 
      serviceAccountName: harness-default
      securityContext:
        runAsUser: 999
        fsGroup: 999
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: copy-config
          image: busybox:1.33.1
          imagePullPolicy: "IfNotPresent"
          command:
            - "sh"
          args:
            - "-c"
            - |
              set -e
              set -x

              cp /configdb-readonly/mongod.conf /data/configdb/mongod.conf
              cp /keydir-readonly/key.txt /data/configdb/key.txt
              chmod 600 /data/configdb/key.txt
          volumeMounts:
            - name: workdir
              mountPath: /work-dir
            - name: config
              mountPath: /configdb-readonly
            - name: configdir
              mountPath: /data/configdb
            - name: keydir
              mountPath: /keydir-readonly
          resources:
            {}
            
        - name: install
          image: harness/mongodb-install:0.8
          args:
            - --work-dir=/work-dir
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: workdir
              mountPath: /work-dir
          resources:
            {}
            
        - name: bootstrap
          image: harness/mongo:4.2.8
          command:
            - /work-dir/peer-finder
          args:
            - -on-start=/init/on-start.sh
            - "-service=mongodb-replicaset-chart"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: REPLICA_SET
              value: rs0
            - name: TIMEOUT
              value: "180"
            - name: SKIP_INIT
              value: "false"
            - name: AUTH
              value: "true"
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: "mongodb-replicaset-chart-admin"
                  key: user
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "mongodb-replicaset-chart-admin"
                  key: password
          volumeMounts:
            - name: workdir
              mountPath: /work-dir
            - name: init
              mountPath: /init
            - name: configdir
              mountPath: /data/configdb
            - name: datadir
              mountPath: /data/db
#                 
          resources:
            {}
            
      containers:
        - name: mongodb-replicaset
          image: harness/mongo:4.2.8
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: mongodb
              containerPort: 27017
          resources:
            limits:
              cpu: '0.5'
              memory: '1024Mi'
            requests:
              cpu: '0.5'
              memory: '1024Mi'
            
          command:
            - mongod
          args:
            - --config=/data/configdb/mongod.conf
            - --dbpath=/data/db
            - --replSet=rs0
            - --port=27017
            - --bind_ip=0.0.0.0
            - --auth
            - --keyFile=/data/configdb/key.txt
            - --wiredTigerCacheSizeGB=0.2
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
          volumeMounts:
            - name: datadir
              mountPath: /data/db
            - name: configdir
              mountPath: /data/configdb
            - name: workdir
              mountPath: /work-dir
#                 

      volumes:
        - name: config
          configMap:
            name: mongodb-replicaset-chart-mongodb
        - name: init
          configMap:
            defaultMode: 0755
            name: mongodb-replicaset-chart-init
        - name: keydir
          secret:
            defaultMode: 0400
            secretName: mongodb-replicaset-chart-keyfile
        - name: workdir
          emptyDir: {}
        - name: configdir
          emptyDir: {}
#           
  volumeClaimTemplates:
    - metadata:
        name: datadir
        annotations:
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: '10Gi'
        storageClassName: 'standard'
---