
apiVersion: v1
kind: Service
metadata:
  name: ng-auth-ui
  labels:
    kots.io/placeholder: 'true'
     
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ng-auth-ui
