
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ng-auth-ui
  annotations:
    kubernetes.io/ingress.class: 'harness'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kots.io/placeholder: 'true'
    
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: ng-auth-ui
              servicePort: 80
            path: /auth(/|$)(.*)
# 
