
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-harness-announce-2
  labels:
    app: redis-sentinel
    kots.io/placeholder: 'true'
     
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  selector:
    release: redis-ha
    app: redis-sentinel
    "statefulset.kubernetes.io/pod-name": redis-sentinel-harness-server-2