
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-harness
  labels:
    app: redis-sentinel
    kots.io/placeholder: 'true'
     
  annotations:
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  selector:
    release: redis-ha
    app: redis-sentinel