
apiVersion: v1
kind: Service
metadata:
  name: timescaledb-single-chart-config
  labels:
    app: timescaledb-single-chart
    chart: timescaledb-single-0.5.5
    release: timescaledb-single-chart
    heritage: Tiller
    cluster-name: timescaledb-single-chart
    kots.io/placeholder: 'true'
    
spec:
  selector:
    app: timescaledb-single-chart
    cluster-name: timescaledb-single-chart
  type: ClusterIP
  clusterIP: None
  ports:
  - name: patroni
    port: 8008
    protocol: TCP
