
apiVersion: v1
kind: Service
metadata:
  name: timescaledb-single-chart
  labels:
    app: timescaledb-single-chart
    chart: timescaledb-single-0.5.5
    release: timescaledb-single-chart
    heritage: Tiller
    cluster-name: timescaledb-single-chart
    role: master
    kots.io/placeholder: 'true'
    
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "4000"    
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    # This always defaults to 5432, even if `!loadBalancer.enabled`.
    port: 5432
    targetPort: postgresql
    protocol: TCP
