

apiVersion: v1
kind: Service
metadata:
  name: harness-ui
  labels:
    kots.io/placeholder: 'true'
     
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: harness-ui
  sessionAffinity: None
  type: ClusterIP