
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: harness-ui
  annotations:
    kubernetes.io/ingress.class: 'harness'
    kots.io/placeholder: 'true'
    
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: harness-ui
              servicePort: 80
            path: /
#              