
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-ui
  labels:
    kots.io/placeholder: 'true'
    
  annotations:  
    kots.io/placeholder: 'true'
             
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: harness-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: harness-ui
        kots.io/placeholder: 'true'
         
      annotations:
        kots.io/placeholder: 'true'
         
        license-features-hash: 'e0b1248bac7a0553702e9d25196df25a9f4e3cd7343bac84f243edcedeb2e46a'         
    spec:
#                  
      serviceAccountName: harness-default
      containers:
      - envFrom:
        - configMapRef:
            name: ui
        image: harness/ui-signed:73701
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 101
          runAsNonRoot: true 
        name: ui
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: '0.2'
            memory: '200Mi'
          requests:
            cpu: '0.2'
            memory: '200Mi'
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
---