apiVersion: kots.io/v1beta1
kind: Installation
metadata:
  creationTimestamp: null
  name: harness-ng
spec:
  channelID: 1pDw5XHodj8dxXxGYnqRLRpdPvA
  channelName: Unstable
  knownImages:
  - image: harness/cv-nextgen:74410
    isPrivate: true
  - image: harness/ci-scm-signed:release-45
  - image: harness/nextgenui-signed:0.292.8
  - image: harness/template-service-signed:74410
    isPrivate: true
  - image: harness/ti-service-signed:release-46
    isPrivate: true
  - image: harness/log-service-signed:release-18
  - image: minio/minio:RELEASE.2022-01-08T03-11-54Z
  - image: harness/pipeline-service-signed:74410
  - image: harness/le-nextgen-signed:66300
    isPrivate: true
  - image: harness/ng-manager-signed:74410
  - image: harness/platform-service-signed:74410
  - image: harness/cdcdata-signed:74410
    isPrivate: true
  - image: harness/ci-manager-signed:74410
    isPrivate: true
  - image: harness/accesscontrol-service-signed:74400
  releaseNotes: 'GitHub Action release of refs/heads/Unstable triggered by gunascode:
    [3007d9a](https://github.com/wings-software/harness-ng-replicated/commit/3007d9a738b53330c58f1dfec06c1d507ec550ac)'
  updateCursor: "207"
  versionLabel: Unstable-3007d9a
status: {}
